//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackTruck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int review_id { get; set; }
        public int user_id { get; set; }
        public int foodtruck_id { get; set; }
        public string content { get; set; }
        public string title { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual foodtrucks foodtrucks { get; set; }
        public virtual users users { get; set; }
    }
}
