//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackTruck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_records
    {
        public int sales_record_id { get; set; }
        public int employee_id { get; set; }
        public double value { get; set; }
        public System.DateTime date { get; set; }
        public string content { get; set; }
    
        public virtual employees employees { get; set; }
    }
}
